workflows:
  ios-workflow:
    name: iOS Build (Flutter)
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean project
        script: |
          flutter clean
          flutter pub get
      - name: Install iOS pods
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod deintegrate
          pod setup
          pod repo update
          pod install
          cd ..
      - name: Build iOS (no code signing)
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
