workflows:
  ios-workflow:
    name: Build iOS App
    environment:
      flutter: stable
      xcode: latest
    scripts:
      # Pre-build script pour nettoyer les pods et installer les dépendances
      - name: Pre-build
        script: |
          rm -rf ios/Pods ios/Podfile.lock
          flutter clean
          flutter pub get
          cd ios
          pod repo update
          pod install
          cd ..
      # Build Flutter pour iOS
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
