workflows:
  ios-workflow:
    name: Build iOS App
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Prebuild
        script: |
          rm -rf ios/Pods ios/Podfile.lock
          flutter clean
          flutter pub get
          cd ios
          pod repo update
          pod install
          cd ..
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
