// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBECnLmI4tRuM6-fzJqfH3BGC2PIcRCUsQ',
    appId: '1:229235939623:web:e71f22dd54496c5508b102',
    messagingSenderId: '229235939623',
    projectId: 'fir-b4c91',
    authDomain: 'fir-b4c91.firebaseapp.com',
    storageBucket: 'fir-b4c91.firebasestorage.app',
    measurementId: 'G-FKRWE5RPMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV4-Ufm7yjLukNbk4Usywwa1KY9Thi7dI',
    appId: '1:229235939623:android:708749bfdfb0a7b308b102',
    messagingSenderId: '229235939623',
    projectId: 'fir-b4c91',
    storageBucket: 'fir-b4c91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVXeKGlYgpq_lOc8-MiCCNjkQ7oDt7pyU',
    appId: '1:229235939623:ios:5c5021b8968b5ed808b102',
    messagingSenderId: '229235939623',
    projectId: 'fir-b4c91',
    storageBucket: 'fir-b4c91.firebasestorage.app',
    iosClientId: '229235939623-ket3j8book95g1l93idua216clenb9fv.apps.googleusercontent.com',
    iosBundleId: 'com.example.tesiaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVXeKGlYgpq_lOc8-MiCCNjkQ7oDt7pyU',
    appId: '1:229235939623:ios:5c5021b8968b5ed808b102',
    messagingSenderId: '229235939623',
    projectId: 'fir-b4c91',
    storageBucket: 'fir-b4c91.firebasestorage.app',
    iosClientId: '229235939623-ket3j8book95g1l93idua216clenb9fv.apps.googleusercontent.com',
    iosBundleId: 'com.example.tesiaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBECnLmI4tRuM6-fzJqfH3BGC2PIcRCUsQ',
    appId: '1:229235939623:web:969ec33fb14cb39308b102',
    messagingSenderId: '229235939623',
    projectId: 'fir-b4c91',
    authDomain: 'fir-b4c91.firebaseapp.com',
    storageBucket: 'fir-b4c91.firebasestorage.app',
    measurementId: 'G-XK87DLT0KN',
  );
}
