# Uncomment this line to define a global platform for your project
platform :ios, '15.0'

use_frameworks!
use_modular_headers!

# This ensures that Flutter plugins are integrated properly
install! 'cocoapods', :deterministic_uuids => false

flutter_application_path = '../'
load File.join(flutter_application_path, '.flutter-plugins-dependencies')

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
